const dummyData = [
  { Name: 'John Doeng', Age: 25, City: 'New York' },
  { Name: 'Jane Smith', Age: 30, City: 'Los Angeles' },
  { Name: 'Bob Johnson', Age: 22, City: 'Chicago' },
  { Name: 'Alice Brown', Age: 28, City: 'San Francisco' },
  { Name: 'Charlie Wilson', Age: 35, City: 'Seattle' },
  { Name: 'Eva Davis', Age: 29, City: 'Miami' },
  { Name: 'Frank Miller', Age: 32, City: 'Dallas' },
  { Name: 'Grace White', Age: 26, City: 'Denver' },
  { Name: 'Henry Taylor', Age: 31, City: 'Boston' },
  { Name: 'Ivy Turner', Age: 24, City: 'Atlanta' },
  { Name: 'Jack Harris', Age: 27, City: 'Phoenix' },
  { Name: 'Kelly Martinez', Age: 33, City: 'San Diego' },
  { Name: 'Leo Robinson', Age: 29, City: 'Houston' },
  { Name: 'Mia Lee', Age: 28, City: 'Portland' },
  { Name: 'Nathan Clark', Age: 26, City: 'Austin' },
  { Name: 'Olivia Hall', Age: 30, City: 'Philadelphia' },
  { Name: 'Paula Turner', Age: 34, City: 'Detroit' },
  { Name: 'Quincy Brooks', Age: 23, City: 'Minneapolis' },
  { Name: 'Rachel Brown', Age: 31, City: 'Charlotte' },
  { Name: 'Samuel Carter', Age: 27, City: 'Nashville' },
  { Name: 'Tina Garcia', Age: 25, City: 'Orlando' },
  { Name: 'Ulysses Foster', Age: 29, City: 'Las Vegas' },
  { Name: 'Violet Collins', Age: 28, City: 'Raleigh' },
  { Name: 'Walter Hall', Age: 32, City: 'San Antonio' },
  { Name: 'Xander Murphy', Age: 26, City: 'Columbus' },
  { Name: 'Yasmine Allen', Age: 30, City: 'Kansas City' },
  { Name: 'Zachary Turner', Age: 33, City: 'Tampa' },
  { Name: 'Abigail Ward', Age: 24, City: 'St. Louis' },
  { Name: 'Benjamin Simmons', Age: 29, City: 'Salt Lake City' },
  { Name: 'Catherine Price', Age: 28, City: 'Indianapolis' },
  { Name: 'David Mitchell', Age: 31, City: 'Pittsburgh' },
  { Name: 'Emma Davis', Age: 27, City: 'Baltimore' },
  { Name: 'Freddie Martinez', Age: 25, City: 'Oakland' },
  { Name: 'Gabriella Baker', Age: 34, City: 'Memphis' },
];

export default dummyData;
